service: hamid-rayka-assignment

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: rayka_assignment.wsgi.application
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
    zip: true
    fileName: requirements.txt

provider:
  name: aws
  role: arn:aws:iam::255248854465:role/Hossein.Mzfr
  profile: rayka
  runtime: python3.11
  region: eu-north-1
  deploymentBucket:
    name: hamidraykadeployment

functions:
  - app:
      handler: wsgi_handler.handler
      events:
        - http: ANY /

package:
  individually:
    true
  exclude:
    - .env
    - .git/**
    - .github/**
    - .serverless/**
    - static/**
    - .cache/**
    - .pytest_cache/**
    - node_modules/**
