# Generated by Django 4.2.6 on 2023-10-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='serial',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
